# Generated by Django 3.2.3 on 2021-08-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=20)),
                ('address2', models.TextField(max_length=20)),
                ('city', models.TextField(max_length=20)),
                ('state', models.TextField(max_length=20)),
                ('password', models.TextField(max_length=20)),
            ],
        ),
    ]
