# Generated by Django 3.2.3 on 2021-08-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('release_date', models.DateField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
